---
- name: Install Elasticsearch
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - elasticsearch 

- name: set elasticsearch.yml
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line : "network.host: [_local_, _site_]"

- name: Set Elasticsearch jvm.options
  replace:
    path: /etc/elasticsearch/jvm.options
    regexp: '-Xmx1g'
    replace: "-Xmx{{es_mem}}g"
  notify: "restart elasticsearch"

- name: Set Elasticsearch jvm.options
  replace:
    path: /etc/elasticsearch/jvm.options
    regexp: '-Xms1g'
    replace: "-Xms{{es_mem}}g"
  notify: "restart elasticsearch"

- name: enable elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes