- name: Install Kibana
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - "kibana={{ es_version }}"

- name: set kibana.yml
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: "server.host: 0.0.0.0"

- name: enable kibana service
  service:
    name: kibana
    state: started
    enabled: yes