- name: Install Kibana
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - "kibana={{ es_version }}"

- name: set kibana.yml
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: "server.host: 0.0.0.0"

- name: enable kibana service
  service:
    name: kibana
    state: started
    enabled: yes

- set_fact:
    export: "{{ role_path}}/files/export.json"
    
- name: Import Kibana Saved Objects
  uri:
    url: http://localhost:5601/api/saved_objects/_bulk_create
    method: POST
    body_format: json
    body: "{{ lookup('file', export) }}"
    headers:
      kbn-xsrf: true
  register: result
  retries: 20
  delay: 30
  until: result is success

- name: Set Default Index Pattern
  uri:
    url: http://localhost:5601/api/kibana/settings
    method: POST
    body_format: json
    body: {"changes":{"defaultIndex": "winlogbeat*"}}
    headers:
      kbn-xsrf: true