---
- include: prereq.yml

- include: elasticsearch.yml

- include: logstash.yml

- include: kibana.yml

- include: docker.yml

- include: elastic-hq.yml

- include: ee-outliers.yml
  tags:
  - outliers

- include: sigma.yml
  tags:
  - sigma